export const IconGlyphs = {
  Home:              '\uE17C',
  Search:            '\uF690',
  Settings:          '\uF6AA',
  ArrowLeft:         '\uF15C',
  Navigation:        '\uF561',
  ChevronDown:       '\uF2A6',
  ChevronRight:      '\uF2B3',
  ChevronLeft:       '\uF2AD',
  MoreHorizontal:    '\uE825',
  Dismiss:           '\uF400',
  Checkmark:         '\uF285',
  Info:              '\u{0F085B}',
  Delete:            '\uF34D',
  Mail:              '\uF527',
  Person:            '\uF582',
  Heart:             '\uF47A',
  Save:              '\uF668',
  ArrowUndo:         '\uF19A',
  ArrowRedo:         '\uF16F',
  Cut:               '\uF33B',
  Copy:              '\uF32C',
  ClipboardPaste:    '\uF2C6',
  SelectAll:         '\uEAA7',
  Share:             '\uF6B0',
  Play:              '\uF5C6',
  Pause:             '\uF592',
  Stop:              '\uF73B',
  ArrowForward:      '\uF158',
  ArrowClockwise:    '\uF13E',
  ArrowSync:         '\uF191',
  FolderOpen:        '\uF433',
  Circle:            '\uF2AC',
  Color:             '\uF2E6',
  Globe:             '\uF45B',
  Warning:           '\uF87A',
  Alert:             '\uF105',
  Library:           '\u{0F0403}',
  Important:         '\uF87A',
  Pen:               '\u{0F022B}',
  Brace:             '\uEE92',
  Life:              '\uE589',
  Prologue:          '\u{0F0A14}'
} as const

export type IconName = keyof typeof IconGlyphs
